POST localhost:8080/mapping-consume
Content-Type: application/json

{
  "name" : "chandler"
}

### JSON
POST http://localhost:8080/request-body-json-v3
Content-Type: application/json

{
  "username" : "chandler",
  "age" : 31
}

